[package]
name = "header-accumulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy-primitives.workspace = true
base64.workspace = true
clap.workspace = true
ethportal-api.workspace = true
firehose-protos.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tracing.workspace = true
tree_hash.workspace = true
thiserror.workspace = true

[dev-dependencies]
decoder.workspace = true
tempfile.workspace = true
