# Copyright 2025 Semiotic AI, Inc.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "era-validators"
version = "0.2.0"
edition = "2021"

[dependencies]
era-validation = { version = "0.1.0", path = "../era-validation" }
